[2023-12-10 15:12:28,868] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-10 15:14:08,450] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\¡rea de Trabalho\\MVP_04\\backend\\test_modelos.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-10 15:14:08,662] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-10 15:45:31,273] INFO _log() L122   * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:36,341] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:36] "GET / HTTP/1.1" 302 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:36,397] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:36] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:36,533] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:36] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:36,537] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:36] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:36,583] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:36] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:37,833] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:37] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:38,009] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:38] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:38,040] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:38] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:38,041] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:38] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:38,523] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:38] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 15:45:49,916] WARNING predict() L162  Erro ao adicionar paciente 'Pedro', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py L162 
[2023-12-10 15:45:49,929] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 15:45:49] "POST /paciente HTTP/1.1" 400 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:01,589] INFO _log() L122   * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:10,468] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:07:10] "GET / HTTP/1.1" 302 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:10,537] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:07:10] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:11,621] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:07:11] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:12,234] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:07:12] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:07:26,503] WARNING predict() L162  Erro ao adicionar paciente 'Pedro', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py L162 
[2023-12-10 16:07:26,517] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:07:26] "POST /paciente HTTP/1.1" 400 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:18:04,087] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:18:04] "GET /openapi/static/css/swagger-ui.css.map HTTP/1.1" 404 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:18:04,405] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:18:04] "GET /openapi/static/js/swagger-ui-bundle.js.map HTTP/1.1" 404 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:18:04,426] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:18:04] "GET /openapi/static/js/swagger-ui-standalone-preset.js.map HTTP/1.1" 404 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:19:14,657] ERROR log_exception() L1890 Exception on /paciente [GET] - call_trace=/usr/lib/python3/dist-packages/flask/app.py L1890
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py", line 186, in get_paciente
    paciente = session.query(Paciente).filter(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2912, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 276, in __init__
    self._set_entities(entities)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 288, in _set_entities
    self._raw_columns = [
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 289, in <listcomp>
    coercions.expect(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 651, in _literal_coercion
    self._raise_for_expected(element, argname)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 1139, in _raise_for_expected
    return super()._raise_for_expected(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 710, in _raise_for_expected
    super()._raise_for_expected(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/coercions.py", line 535, in _raise_for_expected
    raise exc.ArgumentError(msg, code=code) from err
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got <class 'model.paciente.Paciente'>.
[2023-12-10 16:19:14,674] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:19:14] "GET /paciente HTTP/1.1" 500 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:21:51,010] WARNING predict() L162  Erro ao adicionar paciente 'Pedro', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py L162 
[2023-12-10 16:21:51,012] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:21:51] "POST /paciente HTTP/1.1" 400 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:23:41,941] WARNING predict() L162  Erro ao adicionar paciente 'Pedro', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py L162 
[2023-12-10 16:23:41,945] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:23:41] "POST /paciente HTTP/1.1" 400 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:24:00,550] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:24:00] "GET / HTTP/1.1" 302 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:24:00,615] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:24:00] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:24:02,646] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:24:02] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:24:02,988] INFO _log() L122  127.0.0.1 - - [10/Dec/2023 16:24:02] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/lib/python3/dist-packages/werkzeug/_internal.py L122 
[2023-12-10 16:24:12,422] WARNING predict() L164  Erro ao adicionar paciente 'Pedro', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/mnt/c/Users/robso/OneDrive/√Årea de Trabalho/MVP_04/backend/app.py L164 
