[2023-12-09 17:17:12,055] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:28:40,646] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\model\\carregador.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:28:40,857] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:29:41,829] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\model\\modelo.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:29:41,963] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:37,933] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:37] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:38,216] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:38] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:38,216] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:38] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:38,222] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:38] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:38,593] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:38] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:38,646] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:38] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:40:45,132] ERROR log_exception() L1449 Exception on /paciente [POST] - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\robso\OneDrive\Área de Trabalho\MVP_04\backend\app.py", line 105, in predict
    paciente = Paciente(
TypeError: Paciente.__init__() missing 1 required positional argument: 'id'
[2023-12-09 17:40:45,148] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:40:45] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:21,254] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\schemas\\paciente_schema.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:21,479] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:24,895] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\app.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:25,129] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,388] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,563] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,618] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,620] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,965] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:28,980] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:28] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:44:35,066] ERROR log_exception() L1449 Exception on /paciente [POST] - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\robso\OneDrive\Área de Trabalho\MVP_04\backend\app.py", line 103, in predict
    paciente = Paciente(
TypeError: Paciente.__init__() missing 1 required positional argument: 'id'
[2023-12-09 17:44:35,066] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:44:35] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:45:02,828] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\schemas\\paciente_schema.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:45:03,052] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:46:06,023] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\schemas\\paciente_schema.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:46:06,237] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
