[2023-12-09 16:56:20,340] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:31,803] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\schemas\\paciente_schema.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:31,950] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,101] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,410] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,447] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,450] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,839] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:33,904] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:33] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 16:56:42,440] ERROR log_exception() L1449 Exception on /paciente [POST] - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\robso\OneDrive\Área de Trabalho\MVP_04\backend\app.py", line 105, in predict
    paciente = Paciente(
TypeError: Paciente.__init__() got an unexpected keyword argument 'outcome'
[2023-12-09 16:56:42,442] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 16:56:42] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:40,537] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\app.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:40,747] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:49,769] INFO _log() L186  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:49,769] INFO _log() L186  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:49,777] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:55,989] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:55] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:56,232] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:56] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:56,248] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:56] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:56,248] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:56] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:56,575] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:56] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:00:56,587] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:00:56] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:01:04,124] ERROR log_exception() L1449 Exception on /paciente [POST] - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\Users\robso\OneDrive\Área de Trabalho\MVP_04\backend\app.py", line 105, in predict
    paciente = Paciente(
TypeError: Paciente.__init__() got an unexpected keyword argument 'outcome'
[2023-12-09 17:01:04,143] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:01:04] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:03:49,942] INFO _log() L186   * Detected change in 'C:\\Users\\robso\\OneDrive\\Área de Trabalho\\MVP_04\\backend\\model\\paciente.py', reloading - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:03:50,282] INFO _log() L186   * Restarting with stat - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:03:55,303] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:03:55] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:04:07,310] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:04:07] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
[2023-12-09 17:04:07,492] INFO _log() L186  127.0.0.1 - - [09/Dec/2023 17:04:07] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\robso\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L186 
